name = "TurbulentAnalysis"
uuid = "f37adf18-5bf0-4610-a1f9-8bd4c89da752"
authors = ["Sam Aucoin", "sam.aucoin@dal.ca"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
