name = "TurbulentAnalysis"
uuid = "f37adf18-5bf0-4610-a1f9-8bd4c89da752"
version = "0.1.1"
authors = ["Sam Aucoin sam.aucoin@dal.ca"]

[workspace]
projects = ["docs"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
ExtraStats = "e63c6cca-01f4-4512-8a9d-7d793fea96eb"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[sources]
ExtraStats = {rev = "main", url = "https://github.com/s-aucoin/ExtraStats.jl"}

[compat]
Dates = "1.11.0, 1.10"
DocumenterTools = "0.1.21"
ExtraStats = "0.1.1"
HypothesisTests = "0.12.2"
LinearAlgebra = "1.12.0, 1.10"
Measurements = "2.14.1"
Random = "1.11.0, 1.10"
StatsBase = "0.34.13"
julia = "1.10.10 - 1.13"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
